### ISSUE TITLE
Download of v3 not possible

### ISSUE THREAD

**Issue by odan** [fullpipe/twig-webpack-extension#11]
If I try to upgrade to v3 via composer I get the following error message:

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package fullpipe/twig-webpack-extension ^3 exists as fullpipe/twig-webpack-extension[dev-fix-depricated-source-method-use, dev-maste
r, v1.0, v1.0.1, v2.0.0, v2.0.1] but these are rejected by your constraint.
```

According to packagist, v3 is not available: https://packagist.org/packages/fullpipe/twig-webpack-extension

![image](https://user-images.githubusercontent.com/781074/71445769-e43d1f80-271c-11ea-9b14-e55038ab6570.png)

**Comment by fullpipe** [comment]
Hello. May be some problems with packagist.

Works fine for me
```bash
composer require fullpipe/twig-webpack-extension
Using version ^3.0 for fullpipe/twig-webpack-extension
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

Try one more time

**Comment by odan** [comment]
Now it works. Thanks.

![image](https://user-images.githubusercontent.com/781074/71487867-eb982200-281d-11ea-83bc-4231a76af4e0.png)
