### ISSUE TITLE
webpack_entry_css inline

### ISSUE THREAD

**Issue by gitrequests** [fullpipe/twig-webpack-extension#17]
Can we generate inline_css instead of link tag?
This is useful in twig blocks were link tags inside body tag is not a good practice. See the [Specification](https://www.w3.org/TR/html401/struct/links.html#edef-LINK).

There is good Extention in TWIG [ twigphp/cssinliner-extra](https://github.com/twigphp/cssinliner-extra) but it does not work with your Extension.

**Comment by fullpipe** [comment]
Hello. That will be easy to do. https://github.com/fullpipe/twig-webpack-extension/blob/709079bf8a757955f7d2c3614c986eda93797cd1/src/Fullpipe/TwigWebpackExtension/TokenParser/EntryTokenParserCss.php#L55 

We just need to pass `file_get_content` instead of `$tag`.
