### ISSUE TITLE
What's the difference between this package and symfony/webpack-endore-bundle?

### ISSUE THREAD

**Issue by marcin-pragmagotech** [fullpipe/twig-webpack-extension#34]
What's the difference between this package and symfony/webpack-endore-bundle?

**Comment by bc-0dp** [comment]
symfony/webpack-encore-bundle has twigs tags, and they are not supported outside symfony. Where this can be used anywhere you use twig.

...At least I came here because I couldn't get encore's twig tags to work in my SLIM application

**Comment by fullpipe** [comment]
Hello!
@bc-0dp is absolutely right. webpack-encore-bundle is not easy to use without symfony ecosystem
